name: Deploy to お名前ドットコム

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: FTP Deploy
        run: |
          sudo apt-get install -y lftp
          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" ${{ secrets.FTP_SERVER }} <<EOF
          mirror -R --delete --verbose --exclude .git . ${{ secrets.FTP_SERVER_DIR }}
          quit
          EOF
